global:
  resolve_timeout: 1m
route:
  receiver: default
  group_by:
  - job
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m
  routes:
  - match:
      security: ddos
    receiver: developer-team-pager
    routes:
    - match:
        severity: critical
      receiver: security-team-pager
  - match:
      error: err
    receiver: developer-team-pager
  - match:
      operation: pod-restart
    receiver: operation-team-pager
  - match:
      operation: low-capacity
    receiver: operation-team-pager
  - match:
      operation: high-latency
    receiver: operation-team-pager
receivers:
- name: 'default'
  sns_configs:
  - sigv4:
      region: ap-southeast-1
      access_key: **masked**
      secret_key: **masked**
    send_resolved: true
    api_url: "https://sns.ap-southeast-1.amazonaws.com"
    topic_arn: arn:aws:sns:ap-southeast-1:**masked**:**topic**
    subject: '[alert]: for ops'
    message: "\nSummary: {{ .CommonAnnotations.summary }}\nDescription: {{ .CommonAnnotations.description }} "
    attributes:
      key: severity
      value: CRITICAL
- name: 'developer-team-pager'
  sns_configs:
  - sigv4:
      region: ap-southeast-1
      access_key: **masked**
      secret_key: **masked**
    send_resolved: true
    api_url: "https://sns.ap-southeast-1.amazonaws.com"
    subject: '[alert]: for developer'
    topic_arn: arn:aws:sns:ap-southeast-1:**masked**:**topic**
    message: "\nSummary: {{ .CommonAnnotations.summary }}\nDescription: {{ .CommonAnnotations.description }} "
- name: 'security-team-pager'
  sns_configs:
  - sigv4:
      region: ap-southeast-1
      access_key: **masked**
      secret_key: **masked**
    send_resolved: true
    api_url: "https://sns.ap-southeast-1.amazonaws.com"
    subject: '[alert]: for security'
    topic_arn: arn:aws:sns:ap-southeast-1:**masked**:**topic**
    message: "\nSummary: {{ .CommonAnnotations.summary }}\nDescription: {{ .CommonAnnotations.description }} "
- name: 'operation-team-pager'
  sns_configs:
  - sigv4:
      region: ap-southeast-1
      access_key: **masked**
      secret_key: **masked**
    send_resolved: true
    api_url: "https://sns.ap-southeast-1.amazonaws.com"
    subject: '[alert]: for ops'
    topic_arn: arn:aws:sns:ap-southeast-1:**masked**:**topic**
    message: "\nSummary: {{ .CommonAnnotations.summary }}\nDescription: {{ .CommonAnnotations.description }} "
